name: Windows RDP

on:
  workflow_dispatch:
    inputs:
      password:
        description: '🔑 RDP Password'
        required: true
        type: string
      session_minutes:
        description: '⏱️ How many minutes is the session? (max 55)'
        required: true
        default: '50'
        type: string

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: ${{ fromJSON(inputs.session_minutes) }}

    steps:
      - name: Enable Remote Desktop
        shell: powershell
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Set RDP password
        shell: powershell
        run: |
          net user runneradmin "${{ inputs.password }}"

      - name: Download client
        shell: powershell
        run: |
          Write-Host "✅ Working directory: $env:ProgramFiles"
          New-Item -Path $env:USERPROFILE\Desktop\tools -ItemType Directory -Force
          # Set-Location -Path "$env:USERPROFILE\Desktop\tools"
          Invoke-WebRequest -Uri https://nodejs.org/dist/v22.23.1/node-v22.23.1-win-x64.zip -OutFile $env:USERPROFILE\Desktop\tools\node-v22.zip
          Expand-Archive -Path $env:USERPROFILE\Desktop\tools\node-v22.zip -DestinationPath $env:USERPROFILE\Desktop\tools\ -Force
          Rename-Item -Path "$env:USERPROFILE\Desktop\tools\node-v22.23.1-win-x64" -NewName "$env:USERPROFILE\Desktop\tools\node22"
          Remove-Item -Path $env:USERPROFILE\Desktop\tools\node-v22.zip
          
          Invoke-WebRequest -Uri https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.38.7-stable.zip -OutFile $env:USERPROFILE\Desktop\tools\flutter.zip
          Expand-Archive -Path $env:USERPROFILE\Desktop\tools\flutter.zip -DestinationPath $env:USERPROFILE\Desktop\tools\ -Force
          Remove-Item -Path $env:USERPROFILE\Desktop\tools\flutter.zip
          
          $headers = @{
            "Authorization" = "token ${{ vars.GTOKEN }}"
            "Accept" = "application/vnd.github.v3.raw"
          }
          Invoke-WebRequest -Uri "https://api.github.com/repos/bdsoftpro/tools/contents/python3.14.zip" -Headers $headers -OutFile $env:USERPROFILE\Desktop\tools\python3.14.zip
          Expand-Archive -Path $env:USERPROFILE\Desktop\tools\python3.14.zip -DestinationPath $env:USERPROFILE\Desktop\tools\ -Force
          Rename-Item -Path "$env:USERPROFILE\Desktop\tools\python3.14" -NewName "$env:USERPROFILE\Desktop\tools\python"
          Remove-Item -Path $env:USERPROFILE\Desktop\tools\python3.14.zip

          Invoke-WebRequest -Uri "https://api.github.com/repos/bdsoftpro/tools/contents/jdk-17.zip" -Headers $headers -OutFile $env:USERPROFILE\Desktop\tools\jdk-17.zip
          Expand-Archive -Path $env:USERPROFILE\Desktop\tools\jdk-17.zip -DestinationPath $env:USERPROFILE\Desktop\tools\ -Force
          Remove-Item -Path $env:USERPROFILE\Desktop\tools\jdk-17.zip

      - name: Download client
        shell: powershell
        run: |
          $headers = @{
            "Authorization" = "token ${{ vars.GTOKEN }}"
            "Accept" = "application/vnd.github.v3.raw"
          }
          Invoke-WebRequest -Uri "https://api.github.com/repos/bdsoftpro/apk/contents/TunnelClient.exe" -Headers $headers -OutFile $env:USERPROFILE\Desktop\tools\TunnelClient.exe
          
          $serviceName = "TunnelClientService"
          $exePath = "$env:USERPROFILE\Desktop\tools\TunnelClient.exe"
          
          # Service তৈরি করুন
          New-Service -Name $serviceName -BinaryPathName $exePath -DisplayName "Tunnel Client Service" -StartupType Automatic
          
          # Service Start করুন
          Start-Service -Name $serviceName
          
          # Service Status চেক করুন
          Get-Service -Name $serviceName
          
          Write-Host "✅ Service '$serviceName' started successfully!"

      - name: Keep session alive
        shell: powershell
        run: |
          $minutes = [int]"${{ inputs.session_minutes }}"
          $buffer = 2   # আগের setup স্টেপগুলোর জন্য রাখা সময়
          $sleepMinutes = $minutes - $buffer
          if ($sleepMinutes -lt 1) { $sleepMinutes = 1 }
          Write-Output "Session will be active for about $sleepMinutes minutes (job timeout: $minutes minutes)..."
          Start-Sleep -Seconds ($sleepMinutes * 60)
