name: VS Code MacOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Download Code Server
        run: |
          mkdir -p ~/.local/lib ~/.config/code-server ~/tools/sdk ~/Project/.vscode
          echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bash_profile
          source ~/.bash_profile
          cat ~/.bash_profile
