name: Anydesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/bdsoftpro/anydesk/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        run: cmd /c start.bat

        name: AnyViewer
        run: | -Command "Invoke-WebRequest https://dl.anyviewer.com/noinstall/AnyViewer.exe -OutFile C:\Users\runneradmin\Desktop\AnyViewer.exe"
          & 'C:\Users\runneradmin\Desktop\AnyViewer.exe'

      - name: Time Counter
        run: Start-Sleep -Seconds 21600
