name: Anydesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          New-Item -Path 'C:\Users\runneradmin\Desktop\software' -ItemType Directory  > null
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/bdsoftpro/anydesk/main/Downloads.bat" -OutFile "C:\Users\runneradmin\Desktop\software\Downloads.bat"
          cmd /c 'C:\Users\runneradmin\Desktop\software\Downloads.bat'
          
      - name: Log In To AnyDesk
        run: cmd /c 'C:\Users\runneradmin\Desktop\software\start.bat'
        
      - name: Time Counter
        run: Start-Sleep -Seconds 21600
