name: Anydesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          New-Item -Path 'C:\Users\runneradmin\Desktop\software' -ItemType Directory
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/bdsoftpro/anydesk/main/Downloads.bat" -OutFile "C:\Users\runneradmin\Desktop\software\Downloads.bat"
          cmd /c 'C:\Users\runneradmin\Desktop\software\Downloads.bat'

      - name: Downloading & Installing AnyViewer
        run: |
          Invoke-WebRequest -Uri "https://dl.anyviewer.com/noinstall/AnyViewer.exe" -OutFile "C:\Users\runneradmin\Desktop\AnyViewer.exe"
          cmd /c start 'C:\Users\runneradmin\Desktop\AnyViewer.exe'

      - name: Downloading & Installing Notepad Plus Plus
        run: |
          Invoke-WebRequest -Uri https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.6.7/npp.8.6.7.Installer.x64.exe -OutFile "C:\Users\runneradmin\Desktop\software\npp.exe"
          Start-Process -FilePath "C:\Users\runneradmin\Desktop\software\npp.exe" -Args "/S" -Verb RunAs -Wait
      - name: Log In To AnyDesk
        run: cmd /c 'C:\Users\runneradmin\Desktop\software\start.bat'
        
      - name: Time Counter
        run: Start-Sleep -Seconds 21600
