name: Test MacOS

on: [push]

jobs:
  setup-macos-gui:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install AnyDesk
        run: |
          brew install --cask anydesk  # Install AnyDesk

      - name: Start AnyDesk Service
        run: |
          /Applications/AnyDesk.app/Contents/MacOS/AnyDesk &
          sudo ln -s /Applications/AnyDesk.app/Contents/MacOS/AnyDesk /usr/local/bin/anydesk
          sleep 5  # Wait for AnyDesk to start
          anydesk --get-id

      - name: Set AnyDesk Password
        run: sudo anydesk --set-password del!@12sha
