name: Test MacOS

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building....
    runs-on: macos-latest
    timeout-minutes: 9999

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Homebrew (Optional)
        run: |
          brew update
          brew install wget

      - name: Install ngrok
        run: |
          brew install ngrok

      - name: Expose TCP service with ngrok
        run: |
          # Replace 22 with the port your service is running on (e.g., 3306 for MySQL, 22 for SSH)
          ngrok tcp 22 --authtoken 1djbHPfErcqCQ95Imsnpu8sJ8yQ_4wyY2FuBJpFhPHStGzn39 &  # Expose SSH on port 22 (or any other TCP service)
          sleep 10  # Wait for ngrok to initialize

      - name: Enable SSH & Set Root Password
        run: |
          sudo systemsetup -setremotelogin on  # Enable SSH
          sudo dscl . -passwd /Users/root del!@12sha  # Set root password
          sudo launchctl load /System/Library/LaunchDaemons/ssh.plist
          sudo launchctl start com.openssh.sshd

      - name: Get ngrok TCP Public URL
        run: |
          # Retrieve the public ngrok TCP URL (ngrok will expose a random port on your ngrok.io)
          ngrok_url=$(curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "ngrok TCP URL: $ngrok_url"

      - name: Setup Session
        run: while :; do sleep 2073600; done
