name: Test

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
      - name: Use Variable
        run: |
          echo "repository variable : ${{ env.BasePath }}"
