name: Test macOS

on: [push]

jobs:
  setup-macos:
    runs-on: self-hosted  # Must use a real macOS machine
    steps:
      - name: Install AnyDesk
        run: brew install --cask anydesk

      - name: Start AnyDesk Service
        run: |
          open -a AnyDesk
          sleep 5  # Wait for AnyDesk to start
          anydesk --get-id

      - name: Set AnyDesk Password
        run: anydesk --set-password "del!@12sha"
