name: Test MacOS

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building....
    runs-on: macos-latest
    timeout-minutes: 9999

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install ngrok
        run: |
          brew install ngrok

      - name: Authenticate ngrok with Auth Token
        run: |
          # Authenticate ngrok with the provided token stored in GitHub Secrets
          echo 1djbHPfErcqCQ95Imsnpu8sJ8yQ_4wyY2FuBJpFhPHStGzn39 | ngrok authtoken

      - name: Start local TCP service
        run: |
          # Start an SSH server or any custom TCP service
          sudo systemsetup -setremotelogin on
          sleep 5  # Give time for the service to start

      - name: Expose TCP service with ngrok
        run: |
          # Replace 22 with the port your service is running on (e.g., 3306 for MySQL, 22 for SSH)
          ngrok tcp 22 &  # Expose SSH on port 22 (or any other TCP service)
          sleep 10  # Wait for ngrok to initialize

      - name: Get ngrok TCP Public URL
        run: |
          # Retrieve the public ngrok TCP URL (ngrok will expose a random port on your ngrok.io)
          ngrok_url=$(curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "ngrok TCP URL: $ngrok_url"
