name: MacOS X RDP
on: 
  workflow_dispatch:
    
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installing .....
      run: source configure.sh "Del674569"
    - name: Setup Session
      run: | 
        while :; do sleep 2073600; done
