name: MacOS X RDP
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installing .....
      run: sudo configure.sh "Del674569"
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
