name: Test Server

on:
  workflow_dispatch:
    inputs:
      tunnel-token:
        description: 'Tunnel Token'
        required: true
        type: string
      header-hostname:
        description: 'Host Name'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download Server
        run: |
          mkdir -p ~/public
          cd ~/
          sudo apt update > /dev/null 2>&1
          sudo apt install libgtk-3-dev > /dev/null 2>&1
          curl -sL --output-dir ~/ -O -H "Authorization: token ${{ vars.GTOKEN }}" https://raw.githubusercontent.com/bdsoftpro/apk/master/websoket
          curl -sL --output-dir ~/public -O -H "Authorization: token ${{ vars.GTOKEN }}" https://raw.githubusercontent.com/bdsoftpro/apk/master/public/index.html
          curl -sL --output-dir ~/public -O -H "Authorization: token ${{ vars.GTOKEN }}" https://raw.githubusercontent.com/bdsoftpro/apk/master/public/style.css
          curl -sL --output-dir ~/public -O -H "Authorization: token ${{ vars.GTOKEN }}" https://raw.githubusercontent.com/bdsoftpro/apk/master/public/achat.js
          chmod +x ./websoket
          ./websoket &
          
      - name: Download CloudFlare
        run: |
          curl -sL -o cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/

      - name: Start Server
        run: |
          cloudflared tunnel --url http://127.0.0.1:8080 --http-host-header ${{ github.event.inputs.header-hostname }} run --token ${{ github.event.inputs.tunnel-token }}
