name: Ubuntu Server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # সর্বশেষ Ubuntu রানার ব্যবহার করুন

    steps:
      # বর্তমান ডিরেক্টরি প্রিন্ট করুন
      - name: Print working directory
        run: pwd

      # এনভায়রনমেন্ট ভেরিয়েবল প্রিন্ট করুন
      - name: Print environment variables
        run: |
          echo "App Version: ${{ vars.FULL_NAME }}"
          java -version

      # একটি কাস্টম স্ক্রিপ্ট চালান
      - name: Run custom script
        run: |
          git clone https://${{ secrets..GTOKEN }}@github.com/bdsoftpro/HTTP-Forwarders.git
          curl -sL -o server.php -H "Authorization: token ${{ secrets..GTOKEN }}" https://raw.githubusercontent.com/bdsoftpro/websockets/master/server.php

      
      # রিপোজিটরির ফাইলগুলি তালিকা করুন
      - name: List files
        run: ls -la
