name: Ubuntu Server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Download System Resource
        run: |
          git clone https://${{ vars.GTOKEN }}@github.com/bdsoftpro/map-server.git .
          sudo apt-get update
          sudo apt-get install osmium-tool

      - name: Map Location Library File
        run: |
          curl -sL -o bangladesh-latest.osm.pbf https://download.geofabrik.de/asia/bangladesh-latest.osm.pbf
          curl -sL -o india-latest.osm.pbf https://download.geofabrik.de/asia/india-latest.osm.pbf
          osmium merge bangladesh-latest.osm.pbf india-latest.osm.pbf -o data.osm.pbf
          rm -f *-latest.osm.pbf
  
      - name: Start Server
        run: |
          chmod +x ctl
          ./ctl "${{ vars.NGROK }}"
