name: Ubuntu Server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Download System Resource
        run: |
          git clone https://${{ vars.GTOKEN }}@github.com/bdsoftpro/map-server.git .

      - name: Map Location Library File
        run: curl -sL -o data.osm.pbf https://download.geofabrik.de/asia/bangladesh-latest.osm.pbf
  
      - name: Strat Server
        run: |
          chmod +x ctl
          ./ctl "${{ vars.NGROK }}"
