name: Ubuntu Server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # সর্বশেষ Ubuntu রানার ব্যবহার করুন

    steps:

      - name: Download System Resource
        run: |
          git clone https://${{ vars.GTOKEN }}@github.com/bdsoftpro/map-server.git .

      - name: Map Location Library File
        run: curl -L --progress-bar -o data.osm.pbf https://download.geofabrik.de/asia-latest.osm.pbf
  
      - name: Strat Server
        run: |
          chmod +x clt
          ./clt "${{ vars.NGROK }}"
