name: VS Code

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download Code Server
        run: |
          curl -fsSL https://code-server.dev/install.sh | sh
          chmod +x code-server
          sudo mv code-server /usr/local/bin/

      - name: Download CloudFlare
        run: |
          curl -sL -o cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/

      - name: Start Server
        run: |
          cloudflared tunnel --url http://127.0.0.1:3000 run --protocol http2 --token ${{ vars.VS_TUNNEL_TOKEN }}
