name: VS Code

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download Code Server
        run: |
          mkdir -p lib ~/tools ~/Project
          curl -sL https://github.com/coder/code-server/releases/download/v${{ vars.VSCODE_VERSION }}/code-server-${{ vars.VSCODE_VERSION }}-linux-amd64.tar.gz | tar -C lib -xz
          sudo mv lib/code-server-${{ vars.VSCODE_VERSION }}-linux-amd64 /usr/local/lib/code-server-${{ vars.VSCODE_VERSION }}
          ln -s /usr/local/lib/code-server-${{ vars.VSCODE_VERSION }}/bin/code-server /usr/local/bin/code-server
          PASSWORD="${{ vars.VSPASSWD }}" code-server --auth password --bind-addr 127.0.0.1:8080 ~/Project &
      - name: Download Flutter and Android
        run: |
          curl -sL -o flutter_linux_3.10.6-stable.tar.xz https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.10.6-stable.tar.xz
          tar -xf flutter_linux_3.10.6-stable.tar.xz -C ~/tools/ > /dev/null 2>&1
          sudo apt-get install android-sdk android-sdk-helper
          mkdir -p ~/.android/sdk
          export ANDROID_SDK_ROOT=~/.android/sdk
          export ANDROID_HOME=$ANDROID_SDK_ROOT
          sudo wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
          unzip commandlinetools-linux-*_latest.zip -d $ANDROID_SDK_ROOT
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install 'ndk;25.2.9519653' 'platforms;android-34' 'build-tools;34.0.0'
          yes | sudo sdkmanager --licenses

      - name: Download CloudFlare
        run: |
          curl -sL -o cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/

      - name: Start Server
        run: |
          cloudflared tunnel --url http://127.0.0.1:8080 run --protocol http2 --token ${{ vars.VS_TUNNEL_TOKEN }}
