name: VS Code

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download Code Server
        run: |
          mkdir -p lib ~/tools/sdk ~/Project/.vscode
          sudo apt update > /dev/null 2>&1
          sudo apt install libgtk-3-dev
          
